# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Application(object):
    def setupUi(self, Application):
        Application.setObjectName("Application")
        Application.setEnabled(True)
        Application.resize(1121, 901)
        font = QtGui.QFont()
        font.setPointSize(10)
        Application.setFont(font)
        self.exitApplication = QtWidgets.QPushButton(Application)
        self.exitApplication.setGeometry(QtCore.QRect(810, 840, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.exitApplication.setFont(font)
        self.exitApplication.setObjectName("exitApplication")
        self.pickDirectory = QtWidgets.QPushButton(Application)
        self.pickDirectory.setGeometry(QtCore.QRect(810, 20, 291, 41))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pickDirectory.sizePolicy().hasHeightForWidth()
        )
        self.pickDirectory.setSizePolicy(sizePolicy)
        self.pickDirectory.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pickDirectory.setFont(font)
        self.pickDirectory.setObjectName("pickDirectory")
        self.showTemperatureDiagram = QtWidgets.QPushButton(Application)
        self.showTemperatureDiagram.setGeometry(QtCore.QRect(810, 250, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.showTemperatureDiagram.setFont(font)
        self.showTemperatureDiagram.setCheckable(False)
        self.showTemperatureDiagram.setChecked(False)
        self.showTemperatureDiagram.setObjectName("showTemperatureDiagram")
        self.clearScene = QtWidgets.QPushButton(Application)
        self.clearScene.setGeometry(QtCore.QRect(810, 200, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clearScene.setFont(font)
        self.clearScene.setCheckable(False)
        self.clearScene.setChecked(False)
        self.clearScene.setObjectName("clearScene")
        self.showDataBase = QtWidgets.QPushButton(Application)
        self.showDataBase.setGeometry(QtCore.QRect(810, 70, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.showDataBase.setFont(font)
        self.showDataBase.setCheckable(False)
        self.showDataBase.setChecked(False)
        self.showDataBase.setObjectName("showDataBase")
        self.chooseUser = QtWidgets.QComboBox(Application)
        self.chooseUser.setGeometry(QtCore.QRect(810, 150, 291, 22))
        self.chooseUser.setObjectName("chooseUser")
        self.chooseUserLabel = QtWidgets.QLabel(Application)
        self.chooseUserLabel.setGeometry(QtCore.QRect(810, 130, 191, 16))
        self.chooseUserLabel.setObjectName("chooseUserLabel")
        self.playButton = QtWidgets.QPushButton(Application)
        self.playButton.setEnabled(False)
        self.playButton.setGeometry(QtCore.QRect(20, 570, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.playButton.setFont(font)
        self.playButton.setObjectName("playButton")
        self.mediaDurationSlider = QtWidgets.QSlider(Application)
        self.mediaDurationSlider.setGeometry(QtCore.QRect(120, 580, 621, 22))
        self.mediaDurationSlider.setOrientation(QtCore.Qt.Horizontal)
        self.mediaDurationSlider.setObjectName("mediaDurationSlider")
        self.userData = QtWidgets.QTextEdit(Application)
        self.userData.setEnabled(True)
        self.userData.setGeometry(QtCore.QRect(20, 630, 731, 261))
        self.userData.setObjectName("userData")

        self.retranslateUi(Application)
        QtCore.QMetaObject.connectSlotsByName(Application)

    def retranslateUi(self, Application):
        _translate = QtCore.QCoreApplication.translate
        Application.setWindowTitle(
            _translate(
                "Application", "Oprogramowanie wspomagające diagnozę objawu Raynauda"
            )
        )
        self.exitApplication.setText(_translate("Application", "Wyjdź z programu"))
        self.exitApplication.setShortcut(_translate("Application", "Esc"))
        self.pickDirectory.setText(_translate("Application", "Wybierz plik wideo"))
        self.showTemperatureDiagram.setText(
            _translate("Application", "Wyświetl wykres zmiany temperatury")
        )
        self.clearScene.setText(_translate("Application", "Wyczyść zaznaczenie"))
        self.showDataBase.setText(
            _translate("Application", "Wyświetl dane z bazy danych")
        )
        self.chooseUserLabel.setText(
            _translate("Application", "Wybierz badanego z listy ID:")
        )
        self.playButton.setText(_translate("Application", "Play"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Application = QtWidgets.QDialog()
    ui = Ui_Application()
    ui.setupUi(Application)
    Application.show()
    sys.exit(app.exec_())
